#Details 

Test_Url: "https://www.cleartrip.com/"
Timeout: 20
From-Location: "Pune"
To-Location: "Bangalore"
Departure-Date: "Wed, 7 Jan,2018"
Adult-Count: "1"
Child-Count: "1"
Infant-Count: "1"
Email-Id: "abc@gmail.com"
Adult-FirstName: "Test1"
Adult-LastName: "User1"
Child-FirstName: "Test2"
Child-LastName: "User2"
Infant-FirstName: "Test3"
Infant-LastName: "User3"
Child-DOB: "4-May-2007"
Infant-DOB: "4-May-2017"
Card-Number: "123445678903"
Card-Holder-Name: "Test User"
Card-CVV: "567"
Card-Expiry: "May-2019"
